spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared
    database: 0
    namespace: icc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/icc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
fs:
  host: 127.0.0.1
  port: 8021
  password: ClueCon

job:
  enabled: true
