project:
  name: start
server:
  port: 9091
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mybatis/**/*.xml

logging:
  config: classpath:logback-spring.xml
  level:
    com:
      springboot: info
    org:
      freeswitch: info
