package com.perkins.icc.domain.event;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * @author: perkins Zhu
 * @date: 2021/8/2 15:23
 * @description:
 **/
@AllArgsConstructor
@Getter
public enum FsEventType {
    CHANNEL_CALLSTATE("CHANNEL_CALLSTATE", ""),
    CHANNEL_CREATE("CHANNEL_CREATE", ""),
    CHANNEL_DESTROY("CHANNEL_DESTROY", ""),
    CHANNEL_STATE("CHANNEL_STATE", ""),
    CHANNEL_ANSWER("CHANNEL_ANSWER", ""),
    CHANNEL_HANGUP("CHANNEL_HANGUP", ""),
    CHANNEL_HANGUP_COMPLETE("CHANNEL_HANGUP_COMPLETE", ""),
    CHANNEL_EXECUTE("CHANNEL_EXECUTE", ""),
    CHANNEL_EXECUTE_COMPLETE("CHANNEL_EXECUTE_COMPLETE", ""),
    CHANNEL_BRIDGE("CHANNEL_BRIDGE", ""),
    CHANNEL_UNBRIDGE("CHANNEL_UNBRIDGE", ""),
    CHANNEL_PROGRESS("CHANNEL_PROGRESS", ""),
    CHANNEL_PROGRESS_MEDIA("CHANNEL_PROGRESS_MEDIA", ""),
    CHANNEL_OUTGOING("CHANNEL_OUTGOING", ""),
    CHANNEL_PARK("CHANNEL_PARK", ""),
    CHANNEL_UNPARK("CHANNEL_UNPARK", ""),
    CHANNEL_APPLICATION("CHANNEL_APPLICATION", ""),
    CHANNEL_HOLD("CHANNEL_HOLD", ""),
    CHANNEL_UNHOLD("CHANNEL_UNHOLD", ""),
    CHANNEL_ORIGINATE("CHANNEL_ORIGINATE", ""),
    CHANNEL_UUID("CHANNEL_UUID", ""),
    BACKGROUND_JOB("BACKGROUND_JOB", ""),
    ;
    private String code;
    private String desc;
}
